### ISSUE TITLE
Tiny problem with defined tags for package

### ISSUE THREAD

**Issue by SimonLSchlee** [florence/diagrama#1]
Hi,

I just randomly saw that there was a very long tag while browsing the package website.
Your package https://pkgs.racket-lang.org/package/diagrama is missing spaces for its tag: 
diagramdrawingfiguregraphicspictimages
https://pkgd.racket-lang.org/pkgn/search?tags=diagramdrawingfiguregraphicspictimages

For your -doc and -lib packages they are separate tags, I imagine that copy&paste didn't work or something. Maybe the package website needs some fix to its user interface, to make copy&paste work? But I am unsure what caused this.

**Comment by florence** [comment]
Oof, thanks! fixed em.
